import Link from "next/link";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
  <html lang="ko">
    <body>
      <div className="min-h-screen bg-black text-white">
        <header className="border-b border-zinc-800 bg-black">
          <div className="mx-auto flex max-w-7xl flex-col gap-4 px-5 py-4 md:flex-row md:items-center md:justify-between">
            <Link href="/" className="text-2xl font-bold">
              📊 AI 투자 어시스턴트
            </Link>

            <nav className="flex flex-wrap gap-2 text-sm">
              {[
                { name: "추천종목", href: "/recommendations" },
                { name: "시장분석", href: "/market" },
                { name: "알림", href: "/alerts" },
                { name: "매매일지", href: "portfolio" },
              ].map((item) => (
                <Link
                  key={item.name}
                  href={item.href}
                  className="rounded-full border border-zinc-700 px-4 py-2 text-zinc-300 hover:bg-zinc-900"
                >
                  {item.name}
                </Link>
              ))}
            </nav>
          </div>
        </header>

        {children}
      </div>
    </body>
  </html>
);
}
